config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # sidekiqのダッシュボード
  mount Sidekiq::Web, at: '/sidekiq'
  # OAuth認証
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy'

  root 'pages/homes#show'
  scope module: :pages do
    resource :home,     only: %i[show]
    resource :setting,  only: %i[show edit update]
  end

  resources :posts, only: %i[destroy]
  scope module: :posts do
    resources :drafts,    only: %i[index create edit update destroy]
    resources :scheduled, only: %i[index create edit update destroy]
    resources :published, only: %i[index create]
  end
  namespace :posts do
    resources :images, only: %i[destroy]
  end

  resources :tags, only: %i[new create edit update destroy], constraints: OnlyAjaxConstraints.new
  scope module: :tags do
    resources :tagged, only: %i[create destroy], constraints: OnlyAjaxConstraints.new
  end
end

app/views/shared/_card_text.html.erb
<div class="card-text-container">
  <% post_card_texts(post).each do |card_text| %>
    <%= card_text %>
  <% end %>
</div>

app/views/shared/_flash_container.html.erb
<div id="alert-message">
  <% if flash[:notice] %>
    <%= render 'shared/flash_success', message: flash[:notice] %>
  <% elsif flash[:alert] %>
    <%= render 'shared/flash_danger', message: flash[:alert] %>
  <% end %>
</div>

app/views/shared/_flash_danger.html.erb
<p class="alert alert-danger"><%= message %></p>

app/views/shared/_flash_dangers.html.erb
<div class="alert alert-danger">
  <% messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</div>

app/views/shared/_flash_success.html.erb
<p class="alert alert-success"><%= message %></p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to "Twitterあうとぷったー", root_path, class: "navbar-brand text-light icon twitter" %>
    <% if logged_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars bars"></i>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "下書き", drafts_path, class: "nav-link text-light icon draft" %>
          </li>
          <li class="nav-item">
            <%= link_to "過去の投稿", published_index_path, class: "nav-link text-light icon published" %>
          </li>
          <li class="nav-item">
            <%= link_to "予約投稿", scheduled_index_path, class: "nav-link text-light icon scheduled" %>
          </li>
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "設定", setting_path, class: "nav-link text-light icon setting" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", logout_path, class: "nav-link text-light icon logout", method: :delete %>
          </li>
        </li>
      </ul>
    </div>
    <% else %>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Twitterでログイン" , "auth/twitter", class: "nav-link text-light icon login", method: :post %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/shared/_modal_container.html.erb
<%# モーダルダイアログのコンテナ %>
<div id="modal-container" class="modal fade" tabindex="-1" aria-labelledby="create-tag" aria-hidden="true"></div>

app/views/shared/_post_form.html.erb
<div class="container">
  <div class="form-group field">
    <%= form_with(scope: :post) do |f| %>
      <%= f.label :content, '投稿', class: "form-label"%>
      <%# TODO 以下をパーシャルとして抜き出して若干DRYにする %>
      <div class="flex-textarea-container mb-3">
        <div class="flex-textarea-dummy" aria-hidden="true"></div>
        <%= f.text_area :content, class: "flex-textarea textarea-valid for-char-count", id:"editing-post-content", required: true, placeholder: '投稿内容' %>
      </div>
      <%# TODO カウントダウンのスタイル %>
      <p id="char-count-down">
        <%= count_down_twitter_text("")%>
      </p>

      <%# TODO スタイルを追加する %>
      <div id="tagged-tag-container">
        <h3>セットしたタグ</h3>
        <ul id="tagged_tags">
          <%= render partial: 'shared/tagged_tag', collection: current_user.tagged_tags %>
        </ul>
      </div>

      <%= f.label :post_at, '投稿日時', class: 'form-label' %>
      <%= f.datetime_field :post_at, class: 'form-control' %>

      <div id="post-form-submit-container" class="d-grid gap-2 d-md-flex mt-3 justify-content-md-end">
        <%= f.button type: :submit, formaction: drafts_path, class: "button button-submit" do %>
          <i class="fa-solid fa-floppy-disk"></i>保存
        <% end %>
        <%= f.button type: :submit, formaction: scheduled_index_path, class: "button button-submit" do %>
          <i class="fas fa-hourglass-half"></i>予約投稿
        <% end %>
        <%= f.button type: :submit, formaction: published_index_path, class: "button button-submit" do %>
          <i class="fa-solid fa-upload"></i>投稿
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%# NOTE: パーシャルが描画された後でないと適切に動作しないため読み込み順に注意する %>
<%= javascript_pack_tag 'shared/post_form' %>

app/views/shared/_resource_non_existent.html.erb
<div class="mx-auto py-3 w-50" >
  <%= resource %>は存在しません
</div>

app/views/shared/_tagged_tag.html.erb
<%# NOTE: カウントダウン用に半角空白を余分に追加しておく %>
<% tagged_tag = tagged_tag || @tagged_tag %>
<li id=<%= tagged_tag_id(tagged_tag) %> class="for-char-count tagged_tag" rows="1" disabled>
  <%= "#{tagged_tag.name} " %>
  <%# アイコンのみ表示する %>
  <%= link_to '', tagged_path(tagged_tag), method: :delete, remote: true, class: "icon trash"%>
</li>

app/views/shared/_tags.html.erb
<ul id="tags" class="list-unstyled ms-2 py-3 pt-md-1">
  <%= render partial: 'shared/tag', collection: current_user.tags %>
  <li id="tag-new" class="mb-1">
    <div id="tag-new-container" class="tag-container">
      <%= link_to '追加', new_tag_path, remote: true, class: "tag-new icon plus" %>
    </div>
  </li>
</ul>

app/views/shared/_time_ago.html.erb
<%# ローカル変数: datetime %>
<% if within_a_day_from_now?(datetime) %>
  <%= "#{time_ago_in_words(datetime)}前" %>
<% else%>
  <%= l(datetime, format: :short) %>
<% end %>