config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # sidekiqのダッシュボード
  mount Sidekiq::Web, at: '/sidekiq'
  # OAuth認証
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy'

  root 'pages/homes#show'
  scope module: :pages do
    resource :home,     only: %i[show]
    resource :setting,  only: %i[show edit update]
  end

  resources :posts, only: %i[destroy]
  scope module: :posts do
    resources :drafts,    only: %i[index create edit update destroy]
    resources :scheduled, only: %i[index create edit update destroy]
    resources :published, only: %i[index create]
  end
  namespace :posts do
    resources :images, only: %i[destroy]
  end

  resources :tags, only: %i[new create edit update destroy], constraints: OnlyAjaxConstraints.new
  scope module: :tags do
    resources :tagged, only: %i[create destroy], constraints: OnlyAjaxConstraints.new
  end
end

app/models/post.rb
class Post < ApplicationRecord
  class PublishedToDraftError < StandardError; end
  class PublishedToScheduledError < StandardError; end
  include OrderableByTimestamp              # タイムタンプで並び替えるため
  include Twitter::TwitterText::Validation  # Twitterのバリデーションのため
  AUTHORIZED_CONTENT_TYPES = %i[png jpg gif webp]
  enum status: { draft: 0, scheduled: 1, published: 2 }

  has_many_attached :images
  has_one :scheduled_post_job, dependent: :destroy, class_name: 'ScheduledPostJob'
  belongs_to :user

  validates :content, presence: true, uniqueness: { scope: :user_id }
  validates :images,
    content_type: AUTHORIZED_CONTENT_TYPES,
    size: { less_than_or_equal_to: 5.megabytes, message: 'は5MB以下にしてください' },
    dimension: { width: { max: 2000 }, height: { max: 2000 } },
    limit: { min: 1, max: 4 }
  validate :content_should_be_valid_twitter_text, if: Proc.new { |post| post.content.present? }
  validate :post_at_cannot_be_blank_if_scheduled_or_published
  validate :post_at_should_be_on_or_after_now, if: Proc.new { |post| post.scheduled? }
  validate :post_at_should_be_within_a_year, if: Proc.new { |post| post.scheduled? }

  # タグのリストを受け取りcontentに追加する
  def add_tags_to_content(tags)
    return if tags.blank?

    tags.each do |tag|
      # タグの前には半角スペースを入れること
      self.content += ' '
      self.content += tag.name
    end
  end

  # to_**! を使うと保存されてしまうため使わない
  # 下書きに変更する
  def to_draft
    raise PublishedToDraftError, '公開済みの投稿を下書きに変更しようとしています' if self.published?
    self.status = :draft
  end

  # 予約済に変更する
  def to_scheduled
    raise PublishedToScheduledError, '公開済みの投稿を予約投稿に変更しようとしています' if self.published?
    self.status = :scheduled
  end

  # 投稿済に変更する(post_atを付与)
  def to_published
    self.status = :published
    self.post_at = Time.current
  end

  # ジョブをセットする
  def set_scheduled_post_job
    job = perform_later_scheduled_post_job
    self.create_scheduled_post_job(job_id: job.provider_job_id)
  end

  # 予約ツイートの更新(ジョブの更新)
  def update_scheduled_tweet
    return unless self.scheduled_post_job

    job = perform_later_scheduled_post_job
    # statusも更新しておく
    # 投稿失敗 → status: failure → 修正して再度予約投稿した場合のため
    self.scheduled_post_job.update!(job_id: job.provider_job_id, status: 'scheduled')
  end

  # 予約ツイートのキャンセル(ジョブの削除)
  def cancel_scheduled_tweet
    return unless self.scheduled_post_job
    self.scheduled_post_job.destroy!
  end

  # 予約ツイートが成功したかどうか判定
  def scheduled_tweet_failure?
    return unless self.scheduled_post_job

    self.scheduled_post_job.failure?
  end

  private
    # バリデーション : contentが有効なtwitter-textであること
    def content_should_be_valid_twitter_text
      # NOTE: valid_tweetは非推奨なのでparse_tweetを使う
      parse_result = parse_tweet(self.content)
      unless parse_result[:valid]
        self.errors[:content] << 'が無効です。'
      end
    end

    # バリデーション(予約投稿 or 投稿済のとき) : post_atは存在しなければならない
    def post_at_cannot_be_blank_if_scheduled_or_published
      if (scheduled? || published?) && post_at.blank?
        errors[:post_at] << 'が必要です。'
      end
    end

    # バリデーション(予約投稿のとき) : post_atが現在、またはそれ以降であること
    def post_at_should_be_on_or_after_now
      return if post_at.nil?

      if post_at <= Time.current
        errors[:post_at] << 'は現在よりも後に設定してください。'
      end
    end

    # バリデーション(予約投稿のとき) : post_atが1年以内であること
    def post_at_should_be_within_a_year
      return if post_at.nil?

      if post_at >= 1.years.from_now
        errors[:post_at] << 'は1年以内に設定してください。'
      end
    end

    # 投稿予約ジョブをセット
    def perform_later_scheduled_post_job
      ReservePostJob.set(wait_until: self.post_at).perform_later(
        self.user, self.id, self.updated_at
      )
    end
end

app/controllers/posts/drafts_controller.rb
class Posts::DraftsController < ApplicationController
  include Tweetable
  before_action :redirect_to_root_if_not_logged_in

  def index
    # indexの場合はdraftsを更新日時の降順で取得する
    @drafts = current_user.drafts_by_recently_updated.
      page(params[:page]).per(10)
  end

  # NOTE: status はデフォルトで draftのため指定不要
  def create
    @draft = current_user.posts.build(draft_params)
    # NOTE: 新規作成の場合, タグ付けされたタグをcontentに追加しておく
    @draft.add_tags_to_content(current_user.tagged_tags)
    if @draft.save
      respond_to do |format|
        format.html { redirect_to root_url, notice: '下書きの保存に成功しました。' }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, alert: '下書きの保存に失敗しました。' }
        format.js { @error_messages = error_messages_with_prefix(@draft, '下書きの保存に失敗しました。') }
      end
    end
  end

  def edit
    @draft = current_user.drafts.find(params[:id])
  end

  def update
    @draft = current_user.drafts.find(params[:id])
    if @draft.update(draft_params)
      respond_to do |format|
        format.html { redirect_to drafts_url, notice: '下書きの更新に成功しました' }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to drafts_url, notice: '下書きの更新に失敗しました' }
        format.js { @error_messages = error_messages_with_prefix(@draft, '下書きの更新に失敗しました。') }
      end
    end
  end

  # NOTE : 下書きから削除 → 予約投稿 or 投稿済 へ
  def destroy
    @draft = current_user.drafts.find(params[:id])

    # params[:to]に渡した値で分岐する
    if params[:to] == 'published'
      self.to_published!
    elsif params[:to] == 'scheduled'
      self.to_scheduled!
    else
      raise ControllerError::UndefinedCondirionalBranchError, '定義されていないtoパラメータが設定されました'
    end
  end

  private

    def draft_params
      params.require(:post).permit(:content, :post_at, images: [])
    end

    # TODO sendメソッドでDRYにできそう
    # 下書きを投稿する(インスタンス変数を直接操作する)
    def to_published!
      @draft.to_published

      # 有効ならツイート, ツイートに成功すれば保存
      if post_tweet(@draft) && @draft.save
        respond_to do |format|
          format.html { redirect_to root_url, notice: '投稿に成功しました' }
          format.js do
            @error_messages = []
            @to = 'published'
          end
        end

      else
        respond_to do |format|
          format.html { redirect_to root_url, alert: '投稿に失敗しました' }
          format.js do
            @error_messages = error_messages_with_prefix(@draft, '投稿に失敗しました。')
            @to = 'published'
          end
        end
      end
    end

    # 下書きを予約投稿へ(インスタンス変数を直接操作する)
    def to_scheduled!
      @draft.to_scheduled

      # NOTE: post_atが無効ならeditに飛ばす
      unless @draft.valid?
        @error_messages = error_messages_with_prefix(@draft, '予約投稿に失敗しました。')
        render :edit, content_type: 'text/javascript' and return
      end

      if @draft.save
        # NOTE: 親(Post)が保存されていない段階で子(Job)を作成・所有することは出来ないため保存後に実行
        @draft.set_scheduled_post_job

        respond_to do |format|
          format.html { redirect_to drafts_url, notice: '予約投稿に成功しました' }
          format.js do
            @error_messages = []
            @to = 'scheduled'
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to drafts_url, alert: '予約投稿に失敗しました' }
          format.js do
            @error_messages = error_messages_with_prefix(@draft, '予約投稿に失敗しました。')
            @to = 'scheduled'
          end
        end
      end
    end
end

app/controllers/posts/images_controller.rb
class Posts::ImagesController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in

  # 画像を削除する
  def destroy
    post = current_user.posts.find(image_params[:post_id])
    @image = post.images.find(image_params[:id])

    if @image.destroy
      respond_to do |format|
        format.html { redirect_to drafts_url, notice: '画像の削除に成功しました' }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to drafts_url, notice: '画像の削除に失敗しました' }
        format.js { @error_messages = error_messages_with_prefix(@image, '画像の削除に失敗しました') }
      end
    end
  end

  private

    def image_params
      params.permit(:id, :post_id)
    end
end

app/controllers/posts/published_controller.rb
class Posts::PublishedController < ApplicationController
  include Tweetable
  before_action :redirect_to_root_if_not_logged_in

  def index
    @published_posts = current_user.published_posts_by_recently_posted.
      page(params[:page]).per(10)
  end

  def create
    @published_post = build_published_post

    if post_tweet(@published_post) && @published_post.save
        respond_to do |format|
          format.html { redirect_to root_url, notice: '投稿に成功しました' }
          format.js do
            @error_messages = []
            @action = 'published'
          end
        end

    else
      respond_to do |format|
        format.html { redirect_to root_url, alert: '投稿に失敗しました。' }
        format.js { @error_messages = @published_post.errors.full_messages.prepend('投稿に失敗しました。') }
      end
    end
  end

  private

    def post_params
      params.require(:post).permit(:content, images: [])
    end

    def build_published_post
      published_post = current_user.posts.build(post_params)
      # NOTE: 新規作成の場合, タグ付けされたタグをcontentに追加しておく
      published_post.add_tags_to_content(current_user.tagged_tags)
      published_post.to_published
      return published_post
    end
end

app/controllers/posts/scheduled_controller.rb
class Posts::ScheduledController < ApplicationController
  include Tweetable
  before_action :redirect_to_root_if_not_logged_in

  def index
    @scheduled_posts  = current_user.scheduled_posts_by_recently_posting
      .page(params[:page]).per(10)
  end

  def create
    @scheduled_post = build_scheduled_post
    if @scheduled_post.save
      # NOTE: 親(Post)が保存されていない段階で子(Job)を作成・所有することは出来ないため保存後に実行
      @scheduled_post.set_scheduled_post_job

      respond_to do |format|
        format.html { redirect_to root_url, notice: "予約投稿に成功しました: 予約日時#{l(post.post_at, format: :short)}" }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, alert: '予約投稿に失敗しました。' }
        format.js { @error_messages = @scheduled_post.errors.full_messages.prepend('予約投稿に失敗しました。') }
      end
    end
  end

  def edit
    @scheduled_post = current_user.scheduled_posts.find(params[:id])
  end

  def update
    @scheduled_post = current_user.scheduled_posts.find(params[:id])
    if @scheduled_post.update(scheduled_params)
      @scheduled_post.update_scheduled_tweet

      respond_to do |format|
        format.html { redirect_to published_index_path, notice: '予約投稿の更新に成功しました' }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to published_index_path, notice: '予約投稿の更新に失敗しました' }
        format.js { @error_messages = error_messages_with_prefix(@scheduled_post, '予約投稿の更新に失敗しました。') }
      end
    end
  end

  # NOTE: 予約投稿から削除 → 下書き or 投稿へ
  def destroy
    @scheduled_post = current_user.scheduled_posts.find(params[:id])

    # params[:to]に渡した値で分岐する
    if params[:to] == 'published'
      self.to_published!
    elsif params[:to] == 'draft'
      self.to_draft!
    else
      raise ControllerError::UndefinedCondirionalBranchError, '定義されていないtoパラメータが設定されました'
    end
  end

  private

    def scheduled_params
      params.require(:post).permit(:content, :post_at, images: [])
    end

    # paramsを元にPostを生成する
    def build_scheduled_post
      post = current_user.posts.build(scheduled_params)
      # NOTE: 新規作成の場合, タグ付けされたタグをcontentに追加しておく
      post.add_tags_to_content(current_user.tagged_tags)
      post.to_scheduled
      return post
    end

    # TODO sendメソッドでDRYにできそう
    # 投稿する(インスタンスを直接操作する)
    def to_published!
      @scheduled_post.to_published

      # 有効ならツイート, ツイートに成功すれば保存
      if post_tweet(@scheduled_post) && @scheduled_post.save
        @scheduled_post.cancel_scheduled_tweet

        respond_to do |format|
          format.html { redirect_to scheduled_index_url, notice: '投稿に成功しました' }
          format.js do
            @error_messages = []
            @to = 'published'
          end
        end

      else
        respond_to do |format|
          format.html { redirect_to scheduled_index_url, alert: '投稿に失敗しました' }
          format.js do
            @error_messages = error_messages_with_prefix(@scheduled_post, '投稿に失敗しました。')
            @to = 'published'
          end
        end
      end
    end

    # 予約投稿を取り消して下書きへ移動する
    def to_draft!
      @scheduled_post.to_draft

      if @scheduled_post.save
        @scheduled_post.cancel_scheduled_tweet

        respond_to do |format|
          format.html { redirect_to scheduled_index_url, notice: '予約投稿の取り消しに成功しました' }
          format.js do
            @error_messages = []
            @to = 'draft'
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to scheduled_index_url, alert: '予約投稿の取り消しに失敗しました' }
          format.js do
            @error_messages = error_messages_with_prefix(@draft, '予約投稿の取り消しに失敗しました。')
            @to = 'draft'
          end
        end
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in

  # postそのものを削除する
  def destroy
    @post = current_user.posts.find(post_params[:id])

    # from 下書き/予約投稿 で分岐する
    if params[:from] == 'draft'
      destroy_draft
    elsif params[:from] == 'scheduled'
      destroy_scheduled_post
    else
      raise ControllerError::UndefinedCondirionalBranchError, '定義されていないfromパラメータが設定されました'
    end
  end

  private

    def post_params
      params.permit(:id)
    end

    # 下書きを削除する
    def destroy_draft
      if @post.destroy
        respond_to do |format|
          format.html { redirect_to drafts_url, notice: '下書きの削除に成功しました' }
          format.js do
            @error_messages = []
            @from = 'draft'
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to drafts_url, notice: '下書きの削除に失敗しました' }
          format.js { @error_messages = error_messages_with_prefix(@post, '下書きの削除に失敗しました') }
        end
      end
    end

    # 予約投稿を削除する
    def destroy_scheduled_post
      # TODO ジョブの削除
      if @post.destroy
        respond_to do |format|
          format.html { redirect_to drafts_url, notice: '予約投稿の削除に成功しました' }
          format.js do
            @error_messages = []
            @from = 'scheduled'
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to drafts_url, notice: '予約投稿の削除に失敗しました' }
          format.js { @error_messages = error_messages_with_prefix(@post, '予約投稿の削除に失敗しました') }
        end
      end
    end
end

app/helpers/posts/drafts_helper.rb
module Posts::DraftsHelper
end

app/helpers/posts/images_helper.rb
module Posts::ImagesHelper
  def image_id(image)
    "image-#{image.id}"
  end
end

app/helpers/posts/published_helper.rb
module Posts::PublishedHelper
end

app/helpers/posts/scheduled_helper.rb
module Posts::ScheduledHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include Twitter::TwitterText::Validation
  MAX_TWEET_LENGTH = 140
  CARD_TEXT_CLASS = 'card-text'

  # Postカードに表示するテキストを配列として返す
  def post_card_texts(post)
    # 改行文字を指すメタ文字を使用して分割
    delimited_contents = post.content.split(/\R/)
    opening_tag, closing_tag = card_text_p_tag

    delimited_contents.map do |content|
      # 例: <p class="card-text">text</p>
      opening_tag + content + closing_tag
    end
  end

  # HTMLにおけるPostのidを返す
  def post_id(post)
    "post-#{post.id}"
  end

  # twitter投稿テキストのカウントダウン(残り入力可能文字数)を返す
  def count_down_twitter_text(text)
    # NOTE: valid_tweetは非推奨なのでparse_tweetを使う
    parse_result = parse_tweet(text)
    weighted_length = parse_result[:weighted_length]
    return MAX_TWEET_LENGTH - to_ja(weighted_length)
  end

  private

    # weithed_lengthを日本版に合わせて変換する
    def to_ja(weighted_length)
      return weighted_length.to_f / 2
    end

    # card-textを指すクラスを持つpタグ
    def card_text_p_tag
      return "<p class='#{CARD_TEXT_CLASS}'>".html_safe, "</p>".html_safe
    end
end

app/views/posts/drafts/_draft.html.erb
<div class="col" id=<%= post_id(draft) %>>
  <div class="card">
    <div class="card-body">
      <%= render('shared/card_text', post: draft) %>
      <%= render('posts/attached_images', post: draft) %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to "編集", edit_draft_path(draft), class: "button button-submit icon edit", remote: true %>
        <%# NOTE: draft → scheduled or published はパラメータにより分岐させる %>
        <%= link_to "予約投稿", draft_path(draft, to: 'scheduled'), method: :delete, remote: true,
          data: { confirm: "投稿を予約しますか?" }, class: "button button-submit icon scheduled" %>
        <%= link_to "投稿", draft_path(draft, to: 'published'), method: :delete, remote: true,
          data: { confirm: "投稿してもよろしいですか?" }, class: "button button-submit icon upload" %>
      </div>
    </div>
    <div class="card-footer text-muted">
      <p class="mb-0">最終更新: <%= render('shared/time_ago', datetime: draft.updated_at) %></p>
      <p class="mb-0">投稿予定: <%= draft.post_at ? "#{l(draft.post_at, format: :short)}" : '未設定' %></p>
    </div>
  </div>
</div>

app/views/posts/drafts/_form.html.erb
<div class="modal-dialog modal-dialog-centered">

  <div class="modal-content">
    <div class="modal-header">
      <%# renderから渡される変数を利用 %>
      <h5 class="modal-title"><%= title %></h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
      <div class="form-group field">
        <%= form_with(model: @draft, url: draft_path(@draft), remote: true) do |f| %>

          <%= f.label :name, "投稿内容", class: "form-label"%>
          <div class="flex-textarea-container mb-3">
            <div class="flex-textarea-dummy" aria-hidden="true"></div>
            <%= f.text_area :content, class: "flex-textarea textarea-valid for-char-count", id: "editing-post-content", required: true, placeholder: '投稿内容' %>
          </div>
          <p id="char-count-down">
            <%= count_down_twitter_text(@draft.content) %>
          </p>

          <div class="form-group">
            <%= f.label :images, '画像の添付( 4枚以下 )', class: 'form-label' %>
            <%= f.file_field :images, class: 'form-control-file', multiple: true %>
          </div>

          <%# 画像の個別削除 %>
          <%= render('posts/attached_images_form', post: @draft) %>

          <div class="form-group">
            <%= f.label :post_at, '投稿予定日時', class: 'form-label' %>
            <%= f.datetime_field :post_at, class: 'form-control' %>
          </div>

          <div id="post-form-submit-container" class="d-grid gap-2 d-md-flex mt-3 justify-content-md-end">
            <%= f.button type: :submit, class: "button button-submit" do %>
              <i class="fa-solid fa-floppy-disk"></i>更新
            <% end %>
            <%= link_to "削除", post_path(@draft, from: :draft), method: :delete, remote: true, data: { confirm: "この下書きを削除してもよろしいですか?" }, class: "button button-danger icon trash"%>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<%# NOTE: パーシャルが描画された後でないと適切に動作しないため読み込み順に注意する %>
<%= javascript_pack_tag 'shared/post_form' %>

app/views/posts/drafts/create.js.erb
// 実行前に空にしておく
$("#alert-message").empty()

<% if @error_messages.blank? %>
  // 成功した場合はクリアする
  $("#editing-post-content").val("");
  // NOTE: valによる変更ではinputイベントが発火しないので明示的に発火させる
  document.getElementById("editing-post-content").dispatchEvent(new Event("input"));
  $("#alert-message").append("<%= j(render('shared/flash_success', message: "下書きの保存に成功しました。" )) %>");
<% else %>
  $("#alert-message").append("<%= j(render('shared/flash_dangers', messages: @error_messages )) %>");
<% end %>

app/views/posts/drafts/destroy.js.erb
// 実行前に空にしておく
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#<%= post_id(@draft) %>").remove();
  // 投稿の場合
  <% if @to == 'published' %>
    $("#alert-message").append("<%= j(render('shared/flash_success', message: "投稿に成功しました。" )) %>");
  // 予約投稿の場合
  <% elsif @to == 'scheduled' %>
    $("#alert-message").append("<%= j(render('shared/flash_success', message: "予約投稿に成功しました。" )) %>");
  <% end %>

<% else %>
  $("#alert-message").append("<%= j(render('shared/flash_dangers', messages: @error_messages )) %>");
<% end %>

app/views/posts/drafts/edit.js.erb
// NOTE: destroyアクションでpost_atが登録されていなかった場合の分岐
<% if @error_messages %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>

// renderで変数を渡すことで要素を動的に変更する
$("#modal-container").html("<%= escape_javascript(render 'form', title: "下書きの編集") %>")
// コードからイベントを発火させることでtextboxのサイズを調整
document.getElementById("editing-post-content").dispatchEvent(new Event("input"));
$("#modal-container").modal("show")

app/views/posts/drafts/index.html.erb
<% provide(:title, '下書き') %>


<h1>下書き</h1>

<% if @drafts.empty? %>
  <%= render 'shared/resource_non_existent', resource: '下書き' %>

<% else %>
  <%=  paginate @drafts %>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @drafts.each do |draft| %>
      <%= render 'draft', draft: draft %>
    <% end %>
  </div>

  <%=  paginate @drafts %>
<% end %>

app/views/posts/drafts/update.js.erb
// 実行前に空にしておく
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#<%= post_id(@draft) %>").replaceWith("<%= j(render('draft', draft: @draft)) %>");
  $("#modal-container").modal("hide");
  $("#alert-message").append("<%= j(render('shared/flash_success', message: "下書きの更新に成功しました。" )) %>");
<% else %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>