config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # sidekiqのダッシュボード
  mount Sidekiq::Web, at: '/sidekiq'
  # OAuth認証
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy'

  root 'pages/homes#show'
  scope module: :pages do
    resource :home,     only: %i[show]
    resource :setting,  only: %i[show edit update]
  end

  resources :posts, only: %i[destroy]
  scope module: :posts do
    resources :drafts,    only: %i[index create edit update destroy]
    resources :scheduled, only: %i[index create edit update destroy]
    resources :published, only: %i[index create]
  end
  namespace :posts do
    resources :images, only: %i[destroy]
  end

  resources :tags, only: %i[new create edit update destroy], constraints: OnlyAjaxConstraints.new
  scope module: :tags do
    resources :tagged, only: %i[create destroy], constraints: OnlyAjaxConstraints.new
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  include Twitter::TwitterText::Validation

  # ハッシュマークから始まらない場合はハッシュマークを付与する
  before_validation :prepend_hashmark_to_name, unless: :name_is_blank_or_start_with_hashmark?
  belongs_to :user
  # Twitterにおけるハッシュタグの最大文字数は100が上限のため
  validates :name, presence: true, length: { maximum: 101 }, uniqueness: { scope: :user_id }
  validates :is_tagged, inclusion: [true, false]
  # タグのバリデーション(TwitterTextを利用)
  validate :name_should_be_valid_hashtag

  private

    # バリデーション : nameが有効なhashtagであること
    def name_should_be_valid_hashtag
      unless valid_hashtag?(self.name)
        self.errors[:name] << 'が無効です。'
      end
    end

    # 先頭にハッシュマークを付与する
    def prepend_hashmark_to_name
      self.name = self.name.prepend('#') if self.name.present?
    end

    # ハッシュマークから始まるかどうか判定する
    def name_is_blank_or_start_with_hashmark?
      if self.name.blank?
        return true
      end
      return self.name.start_with?('#')
    end
end

app/controllers/tags/added_controller.rb
class Tags::AddedController < ApplicationController
  def create
    tag = current_user.tags.find(create_params[:tag_id])
    # 既にaddedの場合は失敗する
    if tag.is_added?
      @status = '既に使用されているタグです。同じタグを使用することは出来ません。'
      return
    end
    @status =  tag.update(is_added: true) ? 'success' : 'failure'
    @tag = tag
  end

  def destroy
    tag = current_user.tags.find(destroy_params[:id])
    unless tag.is_added?
      @status = 'failure'
      return
    end
    @status = tag.update(is_added: false) ? 'success' : 'failure'
    @tag = tag
  end

  private
    def create_params
      params.permit(:tag_id)
    end

    def destroy_params
      params.permit(:id)
    end
end

app/controllers/tags/tagged_controller.rb
class Tags::TaggedController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in

  def create
    tag = current_user.tags.find(tagged_params[:id])
    # 既にtaggedの場合は失敗する
    if tag.is_tagged?
      @error_messages = ['既に使用されているタグです。同じタグを使用することは出来ません。']
      return
    end
    @error_messages =  tag.update(is_tagged: true) ? [] :  error_messages_with_prefix(tag, 'タグのセットに失敗しました。')
    @tag = tag
  end

  def destroy
    tag = current_user.tags.find(tagged_params[:id])
    unless tag.is_tagged?
      @error_messages =  error_messages_with_prefix(tag, 'タグのセット解除に失敗しました。')
      return
    end
    @error_messages = tag.update(is_tagged: false) ? [] :  error_messages_with_prefix(tag, 'タグのセット解除に失敗しました。')
    @tag = tag
  end

  private
    def tagged_params
      params.permit(:id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in

  def new
    @tag = current_user.tags.build
  end

  def create
    @tag = current_user.tags.build(tag_params)
    @error_messages = @tag.save ? [] : error_messages_with_prefix(@tag, 'タグの作成に失敗しました。')
  end

  def edit
    @tag = current_user.tags.find(params[:id])
  end

  def update
    @tag = current_user.tags.find(params[:id])
    # JS表示用
    @error_messages =  @tag.update(tag_params) ? [] : error_messages_with_prefix(@tag, 'タグの更新に失敗しました。')
  end

  def destroy
    @tag = current_user.tags.find(params[:id])
    @error_messages = @tag.destroy ? [] : error_messages_with_prefix(@tag, 'タグの削除に失敗しました。')
  end

  private

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tag_helper.rb
module TagHelper
  def tag_id(tag)
    return "tag-#{tag.id}"
  end

  def tagged_tag_id(tag)
    return "tagged-tag-#{tag.id}"
  end
end

app/helpers/tags/tagged_helper.rb
module Tags::TaggedHelper
end

app/views/tags/_form.html.erb
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <%# renderから渡される変数を利用 %>
      <h5 class="modal-title"><%= title %></h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div class="form-group field">
      <%= form_with(model: @tag, remote: true) do |f| %>
          <%= f.label :name, "タグ名", class: "form-label"%>
        <div class="mb-3">
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%# renderから渡される変数を利用して分岐 %>
          <% if action == 'new' %>
            <%= f.button type: :submit, class: "button button-submit" do %>
              <i class="fa-solid fa-upload"></i>登録
            <% end %>
          <% elsif action == 'edit' %>
            <%= f.button type: :submit, class: "button button-submit" do %>
              <i class="fa-solid fa-floppy-disk"></i>更新
            <% end %>
            <%= link_to "削除", tag_path(@tag), method: :delete, remote: true, data: { confirm: "ハッシュタグを削除してもよろしいですか?" }, class: "button button-danger icon trash"%>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tags/create.js.erb
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#tag-new").before("<%= j(render("pages/homes/tag", tag: @tag)) %>");
  $("#modal-container").modal("hide")
  $("#alert-message").append("<%= j(render('shared/flash_success', message: "タグの作成に成功しました。" )) %>");
<% else %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>

// 約5秒後に消去する
setTimeout(() => {
  $("#alert-message").empty()
}, 5000);

app/views/tags/destroy.js.erb
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#<%= tag_id(@tag) %>").remove();
  $("#<%= tagged_tag_id(@tag) %>").remove();
  $("#modal-container").modal("hide");
  $("#alert-message").append("<%= j(render('shared/flash_success', message: "タグの削除に成功しました。" )) %>");
<% else %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>

// 約5秒後に消去する
setTimeout(() => {
  $("#alert-message").empty()
}, 5000);

app/views/tags/edit.js.erb
<%# renderで変数を渡すことで要素を動的に変更する %>
$("#modal-container").html("<%= escape_javascript(render partial: 'form', locals: { title: "タグの編集", action: "edit" }) %>")
$("#modal-container").modal("show")

app/views/tags/new.js.erb
<%# renderで変数を渡すことで要素を動的に変更する %>
$("#modal-container").html("<%= escape_javascript(render partial: 'form', locals: { title: "新規タグ作成", action: "new" }) %>")
$("#modal-container").modal("show")

app/views/tags/update.js.erb
// 実行前に空にしておく
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#<%= tag_id(@tag) %>").replaceWith("<%= j(render('pages/homes/tag', tag: @tag)) %>");
  $("#<%= tagged_tag_id(@tag) %>").replaceWith("<%= j(render('pages/homes/tagged_tag', tagged_tag: @tag)) %>");
  $("#modal-container").modal("hide");
  $("#alert-message").append("<%= j(render('shared/flash_success',message: "タグの更新に成功しました。" )) %>");
<% else  %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>

// 約5秒後に消去する
setTimeout(() => {
  $("#alert-message").empty()
}, 5000);