config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  # sidekiqのダッシュボード
  mount Sidekiq::Web, at: '/sidekiq'
  # OAuth認証
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  delete '/logout' => 'sessions#destroy'

  root 'pages/homes#show'
  scope module: :pages do
    resource :home,     only: %i[show]
    resource :setting,  only: %i[show edit update]
  end

  resources :posts, only: %i[destroy]
  scope module: :posts do
    resources :drafts,    only: %i[index create edit update destroy]
    resources :scheduled, only: %i[index create edit update destroy]
    resources :published, only: %i[index create]
  end
  namespace :posts do
    resources :images, only: %i[destroy]
  end

  resources :tags, only: %i[new create edit update destroy], constraints: OnlyAjaxConstraints.new
  scope module: :tags do
    resources :tagged, only: %i[create destroy], constraints: OnlyAjaxConstraints.new
  end
end

app/controllers/pages/settings_controller.rb
class Pages::SettingsController < ApplicationController
  before_action :redirect_to_root_if_not_logged_in

  def show
    @setting = current_user.notification_setting
  end

  def edit
    @setting = current_user.notification_setting
  end

  def update
    @setting = current_user.notification_setting
    if @setting.update(setting_params)
      @setting.send("#{@setting.job_action}_check_tweet_job")

      respond_to do |format|
        format.html { redirect_to setting_url, notice: '設定の更新に成功しました' }
        format.js { @error_messages = [] }
      end
    else
      respond_to do |format|
        format.html { redirect_to setting_url, notice: '設定の更新に失敗しました' }
        format.js { @error_messages = error_messages_with_prefix(@setting, '設定の更新に失敗しました。') }
      end
    end
  end

  private

    def setting_params
      params.require(:notification_setting).permit(:can_notify, :notify_at, :interval_to_check)
    end
end

app/helpers/pages/settings_helper.rb
module Pages::SettingsHelper
  def can_notify(setting)
    setting.can_notify? ? 'ON' : 'OFF'
  end

  # NotificationSettingのnotify_atを見やすくする
  def notify_at(setting)
    setting.notify_at ? l(setting.notify_at, format: :hour_and_min) : '設定されていません'
  end

  # NotificationSettingのinterval_to_checkを見やすくする
  def interval_to_check(setting)
    setting.interval_to_check ? "#{setting.interval_to_check}日" : '設定されていません'
  end
end

app/views/pages/settings/_content.html.erb
<div class="setting-item">
  <h5 class="mt-2">通知機能のON/OFF</h5>
  <p>
    <%= can_notify(setting) %>
  </p>
</div>

<div class="setting-item">
  <h5>
    ツイートチェック間隔
    <small class="text-muted">何日ツイートしていなければ通知するか</small>
  </h5>
  <p>
    <%= interval_to_check(setting)  %>
  </p>
</div>

<div class="setting-item">
  <h5>
    通知する時間
  </h5>
  <p>
    <%= notify_at(setting) %>
  </p>
</div>

<div class="setting-item">
  <%= link_to '編集', edit_setting_path, remote: true, class: "button button-submit icon edit" %>
</div>

app/views/pages/settings/_form.html.erb
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <%# renderから渡される変数を利用 %>
      <h5 class="modal-title"><%= title %></h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div class="form-group field">
      <%= form_with(model: @setting, remote: true, url: setting_path) do |f| %>
        <div class="mb-5 d-flex flex-column">
          <%= f.label :can_notify, "通知機能のON/OFF", class: "form-label mr-3"%>
          <%= f.check_box :can_notify %>
        </div>

        <%# TODO f.check_boxの状態で以下の入力欄が切り替わるようなJavaScriptを書く %>
        <div class="mb-5 d-flex flex-column">
          <%= f.label :interval_to_check, "ツイートチェック間隔 (日)", class: "can-change-color form-label" %>
          <%= f.number_field :interval_to_check, class: "can-change-color form-control", min: 1, max: 30 %>
        </div>

        <div class="d-flex flex-column">
          <%= f.label :notify_at, "通知時間", class: "can-change-color form-label mr-3" %>
          <div class="can-change-color"><%= f.time_select :notify_at, class: "form-control", minute_step: 15 %></div>
        </div>


        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%# renderから渡される変数を利用して分岐 %>
            <%= f.button type: :submit, class: "button button-submit" do %>
              <i class="fa-solid fa-floppy-disk"></i>更新
            <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'pages/setting' %>

app/views/pages/settings/edit.html.erb
<h1>Pages::Settings#edit</h1>
<p>Find me in app/views/pages/settings/edit.html.erb</p>

app/views/pages/settings/edit.js.erb
// renderで変数を渡すことで要素を動的に変更する
$("#modal-container").html("<%= j(render 'form', title: "設定の編集") %>")
// コードからイベントを発火させることでcheckboxの状態に応じてスタイルを変更
document.querySelector("input[type=checkbox]").dispatchEvent(new Event("change"));

$("#modal-container").modal("show")

app/views/pages/settings/show.html.erb
<% provide(:title, '設定') %>

<div class="row">
  <div class="col-2"></div>
  <div id="content" class="col">
    <%= render 'content', setting: @setting %>
  </div>
  <div class="col-2"></div>
</div>

app/views/pages/settings/update.html.erb
<h1>Pages::Settings#update</h1>
<p>Find me in app/views/pages/settings/update.html.erb</p>

app/views/pages/settings/update.js.erb
// 実行前に空にしておく
$("#alert-message").empty()

<% if @error_messages.blank? %>
  $("#content").html("<%= j(render('content', setting: @setting)) %>");
  $("#modal-container").modal("hide");
  $("#alert-message").append("<%= j(render('shared/flash_success', message: "設定の更新に成功しました。" )) %>");
<% else %>
  alert("<%= join_words_with_newline(@error_messages) %>");
<% end %>